### ISSUE TITLE
Extend support to mod_harbour project

### ISSUE THREAD

**Issue by jvtecheto** [asistex/Sublime-Text-harbour-Package#2]
Hello

Excellent work, congratulations, but I would like the support for the new mod_harbour product to be extended, see the wiki.

https://github.com/FiveTechSoft/mod_harbour

Tell me how you need the list of functions and commands so that it recognizes them. As you can see, they are few.

A hug

José.

**Comment by asistex** [comment]
> Hello
> Excellent work, congratulations, but I would like the support for the new mod_harbour product to be extended, see the wiki.
> https://github.com/FiveTechSoft/mod_harbour
> 
> Tell me how you need the list of functions and commands so that it recognizes them. As you can see, they are few.
> 
> A hug
> 
> José.

Hi
I don't know anything about mod_harbour's functions so I'm going to need your help.

Are these all the functions you want to add ?

https://github.com/FiveTechSoft/mod_harbour/wiki/Functions-provided-by-the-mod-Harbour

**Comment by jvtecheto** [comment]
Hi.

Yes, for now if, only the Apache API and mod API

also if possible the commands.
TEMPLATE
ENDTEXT

BLOCKS PARAMS
ENDTEXT

For now it would be fine, we would have to add something else, but not 
much more.

Thank you very much for your attention, it would be the first editor 
that mod_harbour supports. Of course I will post your help in the 
forums.

Jose.

------ Mensaje original ------
De: "asistex Carlos" <notifications@github.com>
Para: "asistex/Sublime-Text-harbour-Package" 
<Sublime-Text-harbour-Package@noreply.github.com>
CC: "Jose Vicente Cheto Ortiz" <jvtecheto@gmail.com>; "Author" 
<author@noreply.github.com>
Enviado: 19/10/2020 16:30:53
Asunto: Re: [asistex/Sublime-Text-harbour-Package] Extend support to 
mod_harbour project (#2)

**Comment by asistex** [comment]
Hi
Please test the new snippets and let me know the result.
I've added snippets for mod_harbour. Let me know if you need to add or remove code between the start and end of the commands.
Also added the undocumented functions AP_Body(), AP_HeadersOutSet( "one", "first" ) but I don't know the parameters.
Greetings 

Carlos

**Comment by jvtecheto** [comment]
Thanks Carlos. I'm testing. I'm going to post it on the forum for more people to use.

Greetings

**Comment by asistex** [comment]
Hello
I have added some snippets to insert HTM code in the prgs. They are very basic.
To expand them you must start typing mh + snippet name to avoid conflict with the harbour ones.
Greetings 

**Hola
He agregado algunos snippets para insertar codigo HTM en los prgs. Son muy basicos.
Para expandirlos se debe iniciar tipeando mh + nombre de snippet para evitar conflicto con los de harbour.
Saludos** 
Carlos

**Comment by asistex** [comment]
Added the possibility to use EMMET in harbour code. Read emmet.md file

Agregado la posibilidad de usar EMMET en codigo harbour, Leer emmet.md
